/** Human catalog of the anti-slop appendix. Regexes in rules.ts are the linter. */
export const APPENDIX_GROUPS = [
  {
    id: "openers",
    label: "Openers",
    lede: "The model clears its throat before it speaks. Delete the first sentence.",
    ruleIds: ["throat-clearing", "dive-delve"],
  },
  {
    id: "wrappers",
    label: "Wrappers",
    lede: "If it's important, the sentence already is. Cut the preface.",
    ruleIds: ["ai-hedges"],
  },
  {
    id: "brochure",
    label: "Brochure",
    lede: "Press-release English. These words rarely survive a fact check.",
    ruleIds: ["buzzwords"],
  },
  {
    id: "hedges",
    label: "Hedges",
    lede: "Politeness theater. If they should do it, tell them.",
    ruleIds: ["politeness-theater"],
  },
  {
    id: "ease",
    label: "False ease",
    lede: "Google's most-broken words. They shame the reader when the step isn't obvious.",
    ruleIds: ["simply-just-easy", "please"],
  },
  {
    id: "padding",
    label: "Padding",
    lede: "Three words that mean one word, or a forecast of the page you already opened.",
    ruleIds: ["in-order-to", "leverage-utilize", "no-preannounce"],
  },
] as const;

export const RULE_TELLS: Record<string, string[]> = {
  "throat-clearing": [
    "I'd be happy to",
    "Certainly!",
    "Absolutely!",
    "Of course!",
    "Sure thing!",
    "Great question",
    "As an AI",
    "I hope this helps",
    "Without further ado",
    "Let's get started",
  ],
  "dive-delve": [
    "Let's dive in",
    "Let's delve",
    "Let's explore",
    "Let's take a look",
    "Let's break it down",
    "Let's unpack",
    "delve into",
    "deep dive",
    "take a closer look at",
  ],
  "ai-hedges": [
    "It's important to note",
    "It's worth noting",
    "It should be noted",
    "Needless to say",
    "It goes without saying",
    "As previously mentioned",
    "Rest assured",
  ],
  buzzwords: [
    "cutting-edge",
    "groundbreaking",
    "game-changer",
    "state-of-the-art",
    "next-generation",
    "best-in-class",
    "world-class",
    "seamless",
    "robust",
    "empower",
    "unleash",
    "unlock the potential",
    "elevate your",
    "transform the way",
    "foster",
    "harness",
    "multifaceted",
    "pivotal",
    "tapestry",
    "landscape of",
    "underscores the importance",
    "revolutionize",
    "supercharge",
    "holistic",
    "synergy",
    "paradigm",
    "in today's rapidly evolving",
    "plays a vital role",
    "comprehensive suite",
    "invaluable",
    "moving forward",
    "going forward",
    "at a high level",
    "when it comes to",
  ],
  "politeness-theater": [
    "feel free to",
    "don't hesitate to",
    "you may want to",
    "you might want to",
    "it is recommended that you",
  ],
  "simply-just-easy": ["simply", "easily", "it's easy to", "just click", "just run"],
  please: ["please note", "please click", "please make sure"],
  "in-order-to": [
    "in order to",
    "due to the fact that",
    "in the event that",
    "for the purpose of",
    "at this point in time",
  ],
  "leverage-utilize": ["leverage", "utilize", "facilitate"],
  "no-preannounce": [
    "in this guide",
    "this document will",
    "we will walk you through",
    "let me walk you through",
  ],
};

export const APPENDIX_RULE_IDS: string[] = APPENDIX_GROUPS.flatMap(
  (group) => [...group.ruleIds],
);

export const TESTER_PHRASES = [
  "I'd be happy to help.",
  "It's important to note that the API returns JSON.",
  "Let's dive in and explore the landscape.",
  "A robust, seamless, cutting-edge solution.",
  "Feel free to click Deploy.",
  "In this guide we will walk you through install.",
];
